myip:
  command: "$HOME/Scripts/myip.sh"
q:
  command: "exit 0"
cat:
  command: "bat"
cl:
  command: "clear"
trans:
  command: "trans :ru -b"
xclip:
  command: "xclip -sel clip"
genpass:
  command: "$HOME/Scripts/password-generator.sh --length"
